### ISSUE TITLE
taskExplorer.exclude does not work for ant xml files

### ISSUE THREAD

**Issue by bm-stschneider** [spmeesseman/vscode-taskexplorer#10]
I added a glob for a folder and I still see the ant tasks.

**Comment by spmeesseman** [comment]
Can you send me the value you have for taskExplorer.exclude from your settings.json?

**Comment by spmeesseman** [comment]
nm, i have this fixed, it'll be in 1.9.1 will probably let it go tonight or tomorrow morning (EDT)
