### ISSUE TITLE
Bookmark certain tasks

### ISSUE THREAD

**Issue by drschwabe** [spmeesseman/vscode-taskexplorer#101]
To right click a given task and 'Bookmark it' or perhaps even with a new UI button would be nice for example in the case of a project with 100+ npm scripts it can be difficult to find the one you need. 

One current workaround is to make your 'favorite' npm scripts VS Code tasks but that becomes tedious after a while; currently VS Code has no automatic way to convert a npm script to task (though I did request that as well microsoft/vscode/issues/98854  )

**Comment by drschwabe** [comment]
Regarding microsoft/vscode/issues/98854 so evidently there is a command called  `Task: Configure Task` that if accessed via command-pallette it then lets you choose a script and then will automatically convert it into a task. 

I wonder if it would be possible to call that command and feed it the given script that is being right-clicked on; ie- 
```
Task Explorer
------------------
some script  > (right click menu)  > Add to exlcludes list 
                                   > Configure task 
```
This would suffice as a sufficient 'bookmark' solution and I think works well with the goals of this project; so just thought I'd point it out.  I briefly looked into where your code calls addToExcludes to get some insight into how to add 'Configure task' in the context menu there but currently not so well versed on VS Code extension development; so do forgive me.

**Comment by spmeesseman** [comment]
i will look into this as soon as I have some time, perhaps similar functionality to the current "Last Tasks" feature

**Comment by drschwabe** [comment]
No problem - will certainly take a look at future versions of your plugin.  For now personally, I have switched back to Webstorm.  It has has the concept of 'Saving' a task; you can do this with a little ui button and then that task is bumped up your scripts list; you can also re-order the list of scripts to help manage their priority in the context of UI.

**Comment by DenvE** [comment]
Could that also be used to avoid showing some tasks?  If you make a list of tasks depending on each other, you just want to show the "master" task in the explorer.

ex: tasks a depends on task b that depends on task c, i would just like to show task a

**Comment by spmeesseman** [comment]
released in 2.0 - favorites folder

**Comment by DenvE** [comment]
Hi Scott, the favorites list looks ok.  Is there a reason why it is not structured like in vscode folder?

**Comment by dfliess** [comment]
It would also be great to be able to label (or rename) task as there could be many tasks with the same name.

**Comment by archon810** [comment]
It looks like Favorites (and Last Tasks) are emptied when you press the Refresh button, which is a highly undesirable behavior.
