### ISSUE TITLE
FR: support chars other than dash for grouping

### ISSUE THREAD

**Issue by ray007** [spmeesseman/vscode-taskexplorer#102]
I have a lot of tasks which use `:` for namespacing, i.e. `build:release`.
Would be nice to have grouping work with those too.

**Comment by richarddavenport** [comment]
@ray007 I just created a PR for this #104 because... colons!
@spmeesseman Thoughts?

**Comment by spmeesseman** [comment]
hi , have been very busy lately, but will get to your request and other peoples as well as soon as i can!!
thanks :)

**Comment by spmeesseman** [comment]
closing ticket.  this was added in 1.27 w/ a configurable separator char, thanks to @richarddavenport
