### ISSUE TITLE
Not recognizing root package.json

### ISSUE THREAD

**Issue by Carlos487** [spmeesseman/vscode-taskexplorer#110]
Using:

Visual Studio Code 1.47.2
Windows 10

Problem:

The package.json is not recognized if it doesn't have a scripts block and if you have nested package.json inside other folders (those appear correctly). Not the even the default install command appears.

![2020-07-18 12_41_59-Window](https://user-images.githubusercontent.com/1598555/87858527-1fd74b00-c8f4-11ea-9084-338443b9f2bf.png)

If you add a dummy command in the script block of the package.json it appears, but the install command doesn't appear either.

If you move the package.json inside a folder. It works as expected.

Also, the Gruntfile.js from the root works as expected.

I'm willing to help debugging this issue if necessary. Let me know if you need any other info.

**Comment by spmeesseman** [comment]
shoulda read that more carefully the first itme....  its intended to skip the install task (use 'install' from the context menu), and it is also intended to not show the tree node of there are no tasks
