### ISSUE TITLE
[gulp-load-plugins] Cannot load gulp task configuration!

### ISSUE THREAD

**Issue by mozgbrasil** [spmeesseman/vscode-taskexplorer#112]
Good afternoon

Who can help

I just installed the extension for vscode

The alert was displayed according to the image

![Captura de tela de 2020-08-04 16-13-08](https://user-images.githubusercontent.com/17202780/89334982-c437ec00-d66d-11ea-98fb-f152d912bc0c.png)

Where in the output is displayed

	[gulp-load-plugins] Cannot load gulp task configuration!

**Comment by spmeesseman** [comment]
thats not the gulp provider from the extension, thats the Gulp task provider from VSCode itself.  Hmmm. not so sure this has anything to do with the extension but ill have a look for sure.  if you remove the extension, the error goes away?

**Comment by spmeesseman** [comment]
theres some gulp changes in the next release, please test when that is available (azure pipelines is partially down at the moment, live accident or something)
