### ISSUE TITLE
BUG: Can't find tasks from package.json

### ISSUE THREAD

**Issue by tyler36** [spmeesseman/vscode-taskexplorer#121]
I have 1 project that TaskExplorer refused to show tasks for in the sidebar. I spent some time debugging the issue (toggling settings and extensions). I can reproduce it as followed:

```package.json``
```json
{
    "scripts": {
        "test": "jest"
    }
}
```

1. ✅ ```I:\example\package.json```, I open VSCode at ```example```
2.  [ ] ```I:\static\example\package.json```, I open VSCode at ```example```, TaskExplorer is empty
3. ✅ ```I:\static\package.json```, I open VSCode at ```static``
4. ✅ ```I:\temp\example\package.json```, I open VSCode at ```example```
5.  [ ] ```I:\temp\static\example\package.json```, I open VSCode at ```example```, TaskExplorer is empty
6. ✅ ```I:\temp\staticc\example\package.json```, I open VSCode at ```example```; 
7.  [ ] ```I:\temp\static\hope\example\package.json```, I open VSCode at ```example```, TaskExplorer is empty

So for me, if I open a project that is more than 1 level deep and one of it's parent folders is exactly called ```static``, TaskExplorer will not see any NPM tasks. Hopefully, this is some sort of bug and not a ghost in my machine.

OS: ```Win10```
VSCode: ```1.50```
TaskExplorer:  ```1.27```

**Comment by spmeesseman** [comment]
is this folder by chance being ignored in the list of ignored paths in your settings.json?

**Comment by spmeesseman** [comment]
oh, wasnt thinking, npm tasks, these are provided by VSCode itself, Task Explorer simply displays them.  So check your ignore paths for vscode, or, vscode itself is ignoring this folder
