### ISSUE TITLE
Problems not highlighted when compiling using Makefile

### ISSUE THREAD

**Issue by yannickowow** [spmeesseman/vscode-taskexplorer#123]
Hi, 
First of all, thanks for your extension. 

I would like to open an issue regarding to how your extension is using `problemMatcher` for Makefiles.
I see by default that your problemMatcher is defined as "cpp"(taskProviderMake.ts:296),  but I don't know where it is defined. As is, when compile errors occurs, it does not show in `Problem` panel. 
I think it should be defined as `$gcc` if `C/C++ Extensions` is installed, or it should be defined from your extension.

Thanks in advance.
Regards.

**Comment by spmeesseman** [comment]
problemmatcher isnt supported for any of the task types, sorry.  except for vscode tasks of course since its explicitly defined in the task def.
will look into adding in the future

**Comment by spmeesseman** [comment]
sorry i was wrong, ill have this corrected in next release (via settings, will default to $gcc)

**Comment by yannickowow** [comment]
Hi
Thanks for all ! 
I did add a comment on your commit. Maybe I am wrong, but your code 
```ts     
let cPlusPlusExtension = extensions.getExtension("spmeesseman.vscode-taskexplorer");
```
suggests that you tried to search for C/C++ Extension.
