### ISSUE TITLE
An option to disable auto-refresh

### ISSUE THREAD

**Issue by creage** [spmeesseman/vscode-taskexplorer#124]
I have huge monorepo with a lot of packages, and time to time, when I switch to TaskExplorer pane and want to run some particular task, I cannot do that, as it says 'Busy, please wait' while refreshing the list of tasks. And this could take from 5 to 10 seconds, which is really annoying, since the list of available tasks was not changed since I've opened the VSCode.

Could we please have an option to disable the autorefresh of tasks list, letting users to refresh it manually? 

This should improve the UX a lot.

**Comment by spmeesseman** [comment]
it should only reload when a task file has changed on disk, is this not the case?
