### ISSUE TITLE
Task Explorer icon in npm tasks

### ISSUE THREAD

**Issue by junalmeida** [spmeesseman/vscode-taskexplorer#125]
Even though task explorer is using yarn to run tasks in `package.json`, task explorer shows npm. 

![image](https://user-images.githubusercontent.com/991675/99689797-08989d80-2a4d-11eb-9a93-9e1a0511da07.png)

![image](https://user-images.githubusercontent.com/991675/99689853-16e6b980-2a4d-11eb-9e62-d72b92932a7b.png)

**Comment by lonix1** [comment]
Since that update my npm root node doesn't have an icon at all (that read "n")... :smile:

**Comment by junalmeida** [comment]
I can see the `yarn` icon, however I'm not sure some scripts are not like tree leaves (with wrench icon): 
![image](https://user-images.githubusercontent.com/991675/107525097-1d805b00-6b7c-11eb-92d9-eafd9025b7c6.png)
And I would name the root node as `yarn` or a generic `package.json`. Now it is `npm` with the `yarn` icon.

**Comment by lonix1** [comment]
:laughing:

These things happen...
