### ISSUE TITLE
Project folder ignored using WSL

### ISSUE THREAD

**Issue by selfagency** [spmeesseman/vscode-taskexplorer#128]
When using VS Code on Windows and remoting into WSL, when I attempt to run tasks, it tries to run those tasks in my root user folder, rather than in the project's folder, saying it can't find a package.json in my root folder.

**Comment by tuanquynet** [comment]
The same issue to me. It seem this plugins does not support WSL

**Comment by spmeesseman** [comment]
it doesnt, as i have not used wsl yet, sorry about that

**Comment by spmeesseman** [comment]
dup #94 wsl support
