### ISSUE TITLE
nested groups

### ISSUE THREAD

**Issue by JohnDoe2991** [spmeesseman/vscode-taskexplorer#129]
First, thank you for this great extension! It really helps managing all my tasks in my projects!

I'm working with a quite large C++ project, which can be built with different options and for different targets. Also there are a lot of small scripts to help with reappearing tasks. Here is an example how my tasks in tasks.json look like:
```
build option_a for target 1
build option_a for target 2
build option_b for target 1
build option_b for target 2
add parameter for option_a
add parameter for option_b
...
```
I tried to group them together like so:
```
option_a:build:target1
option_a:build:target2
option_a:scripts:add parameter
option_b:build:target1
option_b:build:target2
option_b:scripts:add parameter
....
```
What I got was this:
```
projectname
    vscode
        option_a
            build:target1
            build:target2
            scripts: add parameter
            ...
        option_b
            build:target1
            build:target2
            scripts: add parameter
            ...
```
I hoped it would look more like this:
```
projectname
    vscode
        option_a
            build
                target1
                target2
                ...
            scripts
                add parameter
                ...
        option_b
            build
                target1
                target2
                ...
            scripts
                add parameter
                ...
```
Did i something wrong or are nested groups not supported? Is there a chance to get support for this?

**Comment by JohnDoe2991** [comment]
I managed to update the taskTree.ts to support nested groups.
I'm an embedded C/C++ programmer and just googled my way through to get this feature done. So I'm not confident enough to create a pull request for my changes. Feel free to take the changes from my fork if they are actually good enough.
Also I only tests VSCode workspace tasks, so I have no idea if other task providers still are working.

**Comment by spmeesseman** [comment]
lol.  ive been trying to work on this for months, I need this to.  One of these weeks Ill get it working, Im almost there.  This next release has the main routine cleaned up, and prepared to make this change now, but trying to figure out some final issues with it still
