### ISSUE TITLE
Tasks from tasks.json do not work if task is missing "command" property. 

### ISSUE THREAD

**Issue by Marsfan** [spmeesseman/vscode-taskexplorer#130]
I have a task that acts as a wrapper for a couple of other tasks. This task does not have a seperate command that it runs. When I try to trigger this task from the sidebar, it will not run. 

Example task

```json
 {
            "label": "Recompile and Upload Test.ino",
            "detail": "Recompiles Test.ino and then uploads the new build.",
            "type": "shell",
            "dependsOrder": "sequence",
            "dependsOn": ["Compile test.ino", "Load test.ino"],
            "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": true,
                "clear": true
            },
            "promptOnClose": true,
            
        }
```
I tried adding `"command": ""`  instead, but that also fails to run. 
However, if I add `"command": "echo done"` to the task, it works fine. 

Not a huge issue, but I would like to be able to see the output from running the previous tasks without having to add a dummy command, and change the presentation options to not overwrite other tasks.

**Comment by spmeesseman** [comment]
i noticed this one too, on the todo list
