### ISSUE TITLE
scripts missing in multi-root workspace

### ISSUE THREAD

**Issue by mzimdars-gms-online-de** [spmeesseman/vscode-taskexplorer#131]
Hi,
we have a multi root workspace.
in all projects there is an npm task called 'start'

we want to create a compound task through 'tasks.json' that runs all 'start' tasks.
To do this, we have to add 'stubs' for the NPM tasks in the same tasks.json.

Unfortunately, the plugin seems to look into the 'type' and 'script' properties instead of the label - and filters out all but one task, because all tasks have type 'npm' and script 'start', but in different directories.

I think it does not make sense to filter those tasks, in any case not if they have different labels.

Example:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "start module1",
            "type": "npm",
            "script": "start",
            "options": {
                "cwd": "${workspaceFolder}/../module1"
            }
        },
        {
            "label": "start module2",
            "type": "npm",
            "script": "start",
            "options": {
                "cwd": "${workspaceFolder}/../module2"
            }
        },
        {
            "label": "start all",
            "dependsOn":["start module1y", "start module2"]
        }
    ]
}
```

of this configuration, only 'start module2' is shown.

Thank you very much!
mz

**Comment by mzimdars-gms-online-de** [comment]
Ah., forgot, our workaround is to add extra spaces in each 'script' property - it is ignored by npm, but all tasks are showing up :-)

**Comment by spmeesseman** [comment]
woops should have noticed when i read this last night

npm tasks are contributed by VSCode, not Task Explorer.  You should file this bug on the VSCode project.

Here is the VSCode NPM detection error output, just open the Output window and check "Tasks" window.  This is VSCode, not the extension.

Error: The npm task detection didn't contribute a task for the following configuration:
{
    "label": "start module2",
    "type": "npm",
    "script": "start",
    "options": {
        "cwd": "${workspaceFolder}/../module2"
    }
}
The task will be ignored.
