### ISSUE TITLE
Default taskExplorer.exclude should include node_modules

### ISSUE THREAD

**Issue by lonix1** [spmeesseman/vscode-taskexplorer#132]
The [default setting](https://github.com/spmeesseman/vscode-taskexplorer/blob/master/package.json#L1233) for `taskExplorer.exclude` should also contain `node_modules`.

That is a very deep directory, and watching it causes inotify errors on my system (linux).

**Comment by spmeesseman** [comment]
task explorer ignores node_modules by default, it doesn't have to be in the excludes, so the problem lies elsewhere.  I suspect youre not ignoring that directory in the main VSCode excludes, which provide the NPM and Workspace tasks, not the extension

**Comment by spmeesseman** [comment]
thinking about that more...  are you saying that once you added that to the excludes the behavior changed?  theres still something else thats causing vscode to provider npm/workspace tasks from there though, this has never been an issue after hundreds of releases

**Comment by lonix1** [comment]
You could be right, it could be vscode or any number of extensions.

So I've been going through them one by one to see which one doesn't ignore node_modules, and I found that this one doesn't ignore it in that config option. I assumed that was the problem.

So to be sure I understand, what you're saying is that regardless of what I put in there, behind the scenes, the extension always ignores node_modules? So `taskExplorer.exclude` is in **addition** to what the extension does on it's own.

**Comment by spmeesseman** [comment]
@lonix1 correct, its in addition, it always adds "ndode_modules" to whatever you have in that array.

VSCode has it's own "exclude" setting for NPM...  Settings -> Npm -> Exclude.  Have you added it there?

**Comment by lonix1** [comment]
Thanks for explaining, it makes sense now.

And thanks for the tip, I've added: `"npm.exclude": "**/node_modules/**"`
