### ISSUE TITLE
Create custom task from a task

### ISSUE THREAD

**Issue by janosimas** [spmeesseman/vscode-taskexplorer#142]
I have some tasks that take arguments, I've seen the run with arguments and it's great.
I wanted to create a custom task based on an existing task that I could:
- add arguments that I use most of the times
- run commands before or after

I don't know how vscode works with this,
my idea is to have in the context menu of a task something like "create custom task...".
This would create a new user task that would call this task or copy the task code to the custom task (less optimal because of updates)

**Comment by spmeesseman** [comment]
u can accomplish both of those things with Workspace/VSCode tasks in tasks.json, so probably wont be adding this, sorry.

**Comment by janosimas** [comment]
@spmeesseman That's exactly the point, to generate the task.json entry.
This can be generated with "configure task" but vscode only shows the name of the task, while the task explorer organizes them and makes them easier to find.
