### ISSUE TITLE
regression "taskExplorer.enableNpm": false

### ISSUE THREAD

**Issue by bonjourjoel** [spmeesseman/vscode-taskexplorer#144]
Hi,
Since today, this option is not working anymore: "taskExplorer.enableNpm": false
I believe the extension has autoupdated or something?
Best regards, I like your extension a lot!
![bug-task-explorer](https://user-images.githubusercontent.com/78134277/109395316-012a3f80-792c-11eb-8767-740451292dc4.png)

**Comment by spmeesseman** [comment]
fixed in 2.0.6 (not released as of rn)

**Comment by bonjourjoel** [comment]
It works! Thanks a lot.
