### ISSUE TITLE
Makefile variables assigned with := are interpreted as rules (tasks)

### ISSUE THREAD

**Issue by reedhedges** [spmeesseman/vscode-taskexplorer#146]
It looks like variables assigned with := in Makefiles are interpreted as rules. 
For example:

    VAR:=foo

Is a variable assignment, but VAR appears as a rule (task).  Happens with whitespace too:

    VAR := foo

And therefore multiple assignments appearing in the Makefile trigger "is already registered" errors, e.g.

    VAR := foo
    VAR := bar

Here is a complete makefile that demonstrates the problem:

    rule1: rule2
	    @echo rule1
    
    rule2:
	    @echo rule2
    
    VAR1=foo
    
    VAR2:=foo
    
    VAR3 := foo
    
    # Uncomment this to trigger "already registered" error:
    #ifdef FLAG
    #VAR4:=foo
    #VAR5 := foo
    #else
    #VAR4:=bar
    #VAR5 := bar
    #endif

**Comment by reedhedges** [comment]
I've started looking into it, any suggestions?  It looks like it's detecting rules by finding lines containing : but not starting with whitespace, a comment or $, and then skips it if it matches patterns for pattern rules etc.  Would it make sense to check lines once against a regular expression that more closely matches what a make non-pattern/non-special rule should be?  Or use a regular expression to find any rule, then use the current checks for special/pattern rules? Thanks.

**Comment by spmeesseman** [comment]
hi...  if u want to drop your makefile here, ill test against it and make some fixes when i get a chance one of these weekends.  or youre always welcome to submit a pr too

**Comment by spmeesseman** [comment]
duh, nm, you already posted something that replicates.  ill look at it when i have some free time

**Comment by reedhedges** [comment]
Hello, was going to work on this a bit but ran into some issues.    I don't know Typescript at all.  I know a bit of Javascript but not too much experience.   How should I build the taskexplorer extension?   Using npm to build I'm getting errors like `Argument of type 'string | TreeItemLabel' is not assignable to parameter of type 'string'` (in `file.ts` line 113) and `Property 'localeCompare' does not exist on tye 'string | TreeItemLabel'`.   Npm is using nodejs version 12.18.2. (I also noticed that it doesn't have String matchAll() either, which I think is a somewhat recent addition to Javascript, so is this version too old?) Thanks.

**Comment by reedhedges** [comment]
I have typescript@3.9.9.

**Comment by reedhedges** [comment]
OK I just added some `toString()` calls and it fixed the 'string | TreeItemLabel' conversion errors.

Here is a change to the Make provider that uses a simpler approach, it just uses one regex to  find each rule and returns that list:  https://github.com/spmeesseman/vscode-taskexplorer/compare/master...reedhedges:fix-makefile-rule-detection

Do you think that's a good way of doing it?   It's a bit conservative about how rules are named, there is a chance it might not match some users' rules if they are particularly weird.  It definitely skips pattern rules and rules with variables in them. 

It does match explicit file names now (e.g. the literal "program.exe:" rule in the test makefile), which I think might be different behavior, but that is useful in some Makefiles.  Could be easily changed.  (Or an option?) 

(Sorry that the diff is a mess, old code is still there just commented out.)

Let me know what you think.

**Comment by reedhedges** [comment]
Here's a better patch, just the make.ts changes  https://github.com/reedhedges/vscode-taskexplorer/commit/301fe109189244f0e28af7f78e4d7b692690d3dd
