### ISSUE TITLE
configure tsc path

### ISSUE THREAD

**Issue by akomm** [spmeesseman/vscode-taskexplorer#148]
There is an option to configure path for - I think - everything, but tsc. Is it possible to add this option? Need to use local version (node_modules/.bin) and have this in workspace configuration.

**Comment by spmeesseman** [comment]
actually, thought about this one, the tsc tasks are provided by the vscode typescript task provider, not TaskExplorer itself (like NPM tasks).  so there's no setting i can add sorry, that'd be a setting you'd find in the VSCode TypeScript settings
