### ISSUE TITLE
Support for Gradle Tasks?

### ISSUE THREAD

**Issue by SupinePandora43** [spmeesseman/vscode-taskexplorer#15]
?

**Comment by spmeesseman** [comment]
can you provide some more info.  do gradle files have particualr extension?  Are they script files or do they contin targets like ant files do?  Can you send a very basic gradle file?  Id rather work off of the info you can provide rather than get it off the net since I have 0 experience with gradle

**Comment by SupinePandora43** [comment]
extension: .gradle, usually named build.gradle
gradle is java (not only) builder/packager tool such as Maven.
.gradle files are Groovy/(sometimes Kotlin) script files

https://www.tutorialspoint.com/gradle/gradle_tasks.htm

**Comment by SupinePandora43** [comment]
https://marketplace.visualstudio.com/items?itemName=cazzar09.Gradle

**Comment by spmeesseman** [comment]
completed initial support, it is in 1.15, it is unreleased but ill release it this weekend sometime after I have some time to do more testing

**Comment by SupinePandora43** [comment]
@spmeesseman thanks your extension is cool!

**Comment by SupinePandora43** [comment]
@spmeesseman pls remove "**/samples/**" from exculding
@spmeesseman extension show only defined in gradle file tasks, but not show tasks from installed in .gradle file plugins

**Comment by francilioaraujo** [comment]
Only user defined tasks are shown. Gradle also have plugins, which add more tasks. In the example file only the 'fatJar' task is shown, but there are a number of tasks, like build, jar, check, eclipse, javadoc etc.
You can check all those tasks running 'gradle -b test.gradle tasks --all' (there's no need to specify the file with the '-b' switch if this file was named build.gradle). Task is a task that show the available tasks. The build, check, jar and javadoc tasks are included with the java plugin and the eclipse task is included with the eclipse plugin.

**Comment by SupinePandora43** [comment]
@francilioaraujo i dont know why peoples using gradlew, i'm just install gradle-all from site with examples.
and yes this extension dont show tasks from plugins(
> @spmeesseman extension show only defined in gradle file tasks, but not show tasks from installed in .gradle file plugins
