### ISSUE TITLE
Include shell scripts with no extension

### ISSUE THREAD

**Issue by mattalexx** [spmeesseman/vscode-taskexplorer#153]
Frequently I have shell scripts with no extension, and the shebang is the thing that decides what type of script it is. Are there any plans to include those types of shell scripts in the list?

Thanks for the awesome bit of software, by the way. Very well done.

**Comment by spmeesseman** [comment]
ill think of best way to do this w/o having to examine the contents of the files, when i get some time of course.  and thanks for the prop, much appreciated

**Comment by mattalexx** [comment]
So I take it the possibility of this feature is off the table?
