### ISSUE TITLE
Different activity indicator for background tasks

### ISSUE THREAD

**Issue by leonid-shevtsov** [spmeesseman/vscode-taskexplorer#157]
If you start a background task, like a server, the Task Explorer list will show it with a spinner until the task is stopped:

<img width="127" alt="screenshot from Leonid 2021-08-08 at 12 31 14@2x" src="https://user-images.githubusercontent.com/116518/128627488-73210e71-cf94-4f69-bf75-0dfbfdd9b347.png">

It would be great to have a non-animated activity indicator for the background tasks, because a spinner attracts too much attention.

Such tasks are specifically marked with `isBackground: true` in `tasks.json`, see [documentation](https://code.visualstudio.com/Docs/editor/tasks#_background-watching-tasks).

**Comment by leonid-shevtsov** [comment]
I found an additional, more tangible reason to have the icon be static: animated icons peg the "Code Helper (GPU)" process to a consistent ~30% CPU on an M1 MacBook Air. (It's not limited to just Task Explorer - any animated icon.)

You can test with a task like this:

```
      {
        "label": "sleep",
        "type": "shell",
        "command": "sleep 1000",
        "isBackground": true
      }
```

**Comment by cyraid** [comment]
In one of the vscode updates I remember seeing a different icon change for running tasks as well, they made it a 'pause' icon if I remember? Would be handy if Task Explorer changed to that, too. ^_^
