### ISSUE TITLE
The task name in the subdirectory is incorrectly displayed.

### ISSUE THREAD

**Issue by tiansin** [spmeesseman/vscode-taskexplorer#16]
![1](https://user-images.githubusercontent.com/4232281/56089414-f5166f80-5ec4-11e9-80a5-5390ccc6a8e2.png)

@spmeesseman 
[gulpfile.zip](https://github.com/spmeesseman/vscode-taskexplorer/files/3077088/gulpfile.zip)

**Comment by spmeesseman** [comment]
ah, sorry, dumb mistake.  i have it fixed already.  Ill let it go tomorrow, i'm over in the U.S. EDT and up late

**Comment by spmeesseman** [comment]
if you change your double quotes around the task name to single quotes itll work, but like i said ill let the new version go tomorrow sometime
