### ISSUE TITLE
Target of make file in workspace not assigned correctly ...

### ISSUE THREAD

**Issue by heilingbrunner** [spmeesseman/vscode-taskexplorer#167]
The targets of two makefiles are not assigned correctly.

<img width="677" alt="make-file-1" src="https://user-images.githubusercontent.com/1827209/150676490-46ba4e11-9e84-415b-aad0-a30e9173c3ba.png">

Regards

**Comment by heilingbrunner** [comment]
There are no package.json files ...

<img width="677" alt="make-file-2" src="https://user-images.githubusercontent.com/1827209/150678291-90084e32-4e83-41df-9f54-a9dde407530c.png">
.

**Comment by spmeesseman** [comment]
hmmm, weird, i cant reproduce, please post your log output?

![te_167](https://user-images.githubusercontent.com/48744816/150909196-baf32e54-be6a-4814-8347-d3cc99a50b54.png)

**Comment by spmeesseman** [comment]
also can u try disabling all other extensions to make sure theres nothing contributing those 2 extra tasks in each folder?

**Comment by heilingbrunner** [comment]
You are right ! A second makefile extension generated the additional entries.

![ok](https://user-images.githubusercontent.com/1827209/151153768-0d8c45f0-31b5-4e0a-a6df-67401cdf7582.png)

Thank you. 👍

**Comment by spmeesseman** [comment]
good deal!!
