### ISSUE TITLE
VSCode output panel keeps popping up [on Tasks]

### ISSUE THREAD

**Issue by joe733** [spmeesseman/vscode-taskexplorer#169]
Looking at https://github.com/microsoft/vscode/issues/33262 makes me think that TaskExpolrer could be causing the issue:

![image](https://user-images.githubusercontent.com/38415384/154988963-31b30216-cb5d-4561-8c68-6353174b3a76.png)
 
 Also extension info does not seem to load.

**Comment by spmeesseman** [comment]
thats not from task explorer, task explorer has its own output window labeled "Task Exlporer", so im not sure what you have thats causing that.  not sure why vsmarketplace isnt serving the readme, maybe intermittent u can check again
