### ISSUE TITLE
Use NSIS v3 logo

### ISSUE THREAD

**Issue by idleberg** [spmeesseman/vscode-taskexplorer#17]
I've just stumbled across this extension and noticed it is still using the old NSIS logo. You can find the NSIS v3 logo on [GitHub](https://github.com/idleberg/nsis-logo) and even [npm](https://www.npmjs.com/package/@nsis/logo). Let me know if you need help, e.g. if you prefer the bitmap icons used by NSIS itself.

**Comment by spmeesseman** [comment]
Ah, I do see now that i looked a little harder, weird that its not really out there in a google search, i didn't know that was the new logo the first time i went to grab it probably.  Ill get it in there in 1.15 i had updated all the icons anyway as i added gradle support.  Thanks for the info!

**Comment by spmeesseman** [comment]
i plan on letting 1.15 go this weekend, so the new icon will be in there.  I just noticed youre the one who wrote the NSIS extension, it is very very helpful thank you!  are you part of the actual nsis project itself?

**Comment by idleberg** [comment]
> are you part of the actual nsis project itself?

I'm not, but I know some of the developers and I've contributed graphics for more than a decade. Also got a couple of related projects, but I haven't used NSIS myself in a looooong time.

**Comment by spmeesseman** [comment]
@idleberg pretty cool youre the one whos done the graphics, ive used nsis for a long time, not a lot but here and there.  do you happen to have the new logo as an svg?  24x24 for using as a tree icon in vscode?

**Comment by idleberg** [comment]
Here are the SVGs:

https://github.com/idleberg/nsis-logo/tree/master/dist/Logo
