### ISSUE TITLE
excluding tsc does not remove the tsc Tasks from Taskexplorer

### ISSUE THREAD

**Issue by CodeAvolition** [spmeesseman/vscode-taskexplorer#170]
this Issue was mentioned as a sidenote by [josh-hemphill](https://github.com/josh-hemphill) in https://github.com/spmeesseman/vscode-taskexplorer/issues/162, 
but since there is no specfic issue to track progress on this i created this.

## Steps to reproduce:
Disable Tsc in settings
![image](https://user-images.githubusercontent.com/65223214/163156200-f4a8f70a-96f8-4648-91ea-03b4a54c4f88.png)
or
"taskExplorer.enableTsc": false,

## expected result:
tsc tasks are hidden in taskExplorer

## actual result:
tsc tasks still get displayed as usual
![image](https://user-images.githubusercontent.com/65223214/163156646-a1d49857-8165-4719-9626-379c1234d21b.png)

**Comment by NMichas** [comment]
+1, tested on v2.9.1, VS Code v1.67.2.

**Comment by JaimeStill** [comment]
Having the same issue on v2.9.1, VS Code 1.70.2

**Comment by CodeAvolition** [comment]
After being very annoyed by this unimportant issue i cloned the project and tried to fix it myself, but lo an behold, while doing that i realized that the issue has been fixed. The fix is just not in the release that can be found in the vscode marketplace.

With Setting on:
![image](https://user-images.githubusercontent.com/65223214/191001451-0e98d570-41e5-4d56-9edc-49e130571c5d.png)
With Setting off:
![image](https://user-images.githubusercontent.com/65223214/191001502-b9ee5492-827e-447a-8f5f-5839cbd811ae.png)
Tested on master branch 19/sep/2022

The latest release on the marketplace is version 2.9.1 which was released on the 05/feb/2022
while the latest commits are from 22/feb/2022
So maybe a new release with all the current changes might fix the problem.

There is also a workaround that worked for me:
taskexplorer uses the default vscode taskdetection so if you turn that off for tsc the folder disappears too

"typescript.tsc.autoDetect": "off"
or in Guid settings:
![image](https://user-images.githubusercontent.com/65223214/191002452-6b1b9f2f-788e-44ff-82d5-2e7c05a08ed9.png)

**Comment by JaimeStill** [comment]
@CodeAvolition Adjusting TSC Auto Detect is helpful, thanks.
