### ISSUE TITLE
Gulp tasks cannot be executed and retrieved

### ISSUE THREAD

**Issue by tiansin** [spmeesseman/vscode-taskexplorer#18]
1.
![1](https://user-images.githubusercontent.com/4232281/56221450-d7036780-609c-11e9-977d-9a444d6be97d.png)

@spmeesseman Cannot identify such a task code with a newline.

2.
I ran the gullp task in the subdirectory and got an error that I couldn't find the gulp binary.
`> Executing task: /Users/johnny/admin2/node_modules/.bin/gulp default <`

My Gulpfile.js is in /Users/johnny/admin2/public/admin directory.

The Gulpf binary is in this directory.
`/Users/johnny/admin2/public/admin/node_modules/.bin/gulp`

**Comment by spmeesseman** [comment]
so we would need a new setting for explicitly setting the path to the gulp program if it is installed globally i think?  or do you know of a better way?  maybe to ask npm if something is installed globally and where?
if you put that path (/Users/johnny/admin2/public/admin/node_modules/.bin) into your system PATH environment variable it should work now though

**Comment by tiansin** [comment]
Sorry, maybe my expression is wrong.
/Users/johnny/admin2 is my project directory
/Users/johnny/admin2/public/admin is a subdirectory of a gulp task. The extension searches for the tasks in my subdirectory correctly, but it is not the binary file node_modules/.bin/gulp in the subdirectory. Instead, the gulp executable file in node_modules under the project root directory is opened.

**Comment by tiansin** [comment]
@spmeesseman  My package.json is in a subdirectory. In my opinion, I should find node_modules/.bin/gulp in the subdirectory and execute it instead of looking for node_modules/.bin/gulp in the project root directory and executing it.

**Comment by spmeesseman** [comment]
Ah ok, I see what you mean.  I'll take a look as soon as I get a bit of free time

**Comment by spmeesseman** [comment]
@tiansin what is the path to your package.json?

**Comment by spmeesseman** [comment]
ah, nm, i see your reference in your gulpfile ./package.json.  I have this fixed, ill put it out tonight or tomorrow EDT

**Comment by spmeesseman** [comment]
@tiansin can you test this for me:

`cd /Users/johnny/admin2`
`npx gulp --gulpfile public/admin/gulpfile.js default`

Does that run your task correctly?

I also didnt see your other comment about the newline messing up the task detection, ill look at that one another time

**Comment by spmeesseman** [comment]
ok that was easy, i have both your issues fixed.  bye bye lunch hour lol.  gotta get back to work but ill let those fixes go tonight or tomorrow
