### ISSUE TITLE
Property batch is not allowed

### ISSUE THREAD

**Issue by lonix1** [spmeesseman/vscode-taskexplorer#185]
Thanks for the latest updates, it's been a while since getting new features. :+1: 

In my config I've added the `"taskExplorer.enabledTasks": { ... }` and it complains for `"batch": false,`:
> Property batch is not allowed

What could be the reason?

**Comment by spmeesseman** [comment]
i see it, its missing in package.json somewhere i need to add it , in the configuration.properties.taskExplorer.enabledTasks object.  ill have a new release out soon, sorry about that
