### ISSUE TITLE
The wrong task was executed.

### ISSUE THREAD

**Issue by tiansin** [spmeesseman/vscode-taskexplorer#19]
![1](https://user-images.githubusercontent.com/4232281/56419493-f7b20400-62cc-11e9-90ea-dd3f9666aed4.gif)

@spmeesseman 
Always perform a 'clean' task

**Comment by spmeesseman** [comment]
Oh man, thats weird, im sorry, Ill get that fixed when i get home from work tonight.  thanks for the vid to show

**Comment by spmeesseman** [comment]
can you provide that gulpfile for me?

**Comment by tiansin** [comment]
@spmeesseman 
[gulpfile.zip](https://github.com/spmeesseman/vscode-taskexplorer/files/3098894/gulpfile.zip)

**Comment by spmeesseman** [comment]
hmmm, i cant reproduce this, your other one you just posted too.  Are you using v1.14.7?

Also, can you turn Debug logging on in TaskExplorer settings, set it to level 2, and send me the output of from the TaskExplorer output window after a tree refresh?

**Comment by tiansin** [comment]
@spmeesseman That's right v1.14.7.

Tree get children
   Build task tree

Processing task 1 of 7
   Added source file container          : npm

Processing task 2 of 7
   Skipping
   enabled                              : true
   is install task                      : true

Processing task 3 of 7
   Added source file container          : gulp

Processing task 4 of 7

Processing task 5 of 7

Processing task 6 of 7

Processing task 7 of 7
   Get task tree

Tree get children
   Get folder task files

Tree get children
   Get file tasks/scripts

Tree get children
   Build task tree

Processing task 1 of 7
   Added source file container          : npm

Processing task 2 of 7
   Skipping
   enabled                              : true
   is install task                      : true

Processing task 3 of 7
   Added source file container          : gulp

Processing task 4 of 7

Processing task 5 of 7

Processing task 6 of 7

Processing task 7 of 7
   Get task tree

Tree get children
   Get folder task files

Tree get children
   Get file tasks/scripts

invalidateTasksCacheGulp

Find gulpfile targets
   found target
      name                              : clean
   found target
      name                              : htmlmin
   found target
      name                              : copy
   found target
      name                              : default
   done

Tree get children
   Build task tree

Processing task 1 of 11
   Added source file container          : gulp

Processing task 2 of 11

Processing task 3 of 11

Processing task 4 of 11

Processing task 5 of 11
   Added source file container          : npm

Processing task 6 of 11
   Skipping
   enabled                              : true
   is install task                      : true

Processing task 7 of 11
   Added source file container          : gulp

Processing task 8 of 11

Processing task 9 of 11

Processing task 10 of 11

Processing task 11 of 11
   Get task tree

Tree get children
   Get folder task files

Tree get children
   Get file tasks/scripts

**Comment by spmeesseman** [comment]
well guess what?  i reproduced, and this is a bug in vscode lol.  see my note in the other issue u posted about gulpfiles in the project root being provided by vscode, not the extension.  when i add functionality to provide the tasks from project root gulpfile internally, this issue will go away.  Subdir tasks should work fine, which the exntension provides internally.

**Comment by spmeesseman** [comment]
this is an easier change than i thought )i couldnt help but to look at it), so i will have this in the next update (1.14.9) tonight or tomorrow.  I put out fix for #20 in 1.14.8 just a little bit ago
