### ISSUE TITLE
Add "**/.venv/**" to exclude by default

### ISSUE THREAD

**Issue by kjaymiller** [spmeesseman/vscode-taskexplorer#191]
VS Code's Python extension now allows for easier [creation of Python Virtual Environments](https://code.visualstudio.com/docs/python/environments#_creating-environments).

Task Explorer finds all the python packages and their associated files which makes it incredibly busy.

The simple solution I found was to add `**/.venv/**` to the exclude list. This is the default venv path used by VS Code.

Could this entry be added to the default list?

I made a video on this and my workaround

https://youtu.be/SV4k1OcqMxA

**Comment by kjaymiller** [comment]
perhaps a bigger change would be to ignore paths that are hidden by default but my PR just solves the immediate problem.

**Comment by spmeesseman** [comment]
pr pulled, thank u
