### ISSUE TITLE
Saving the Gulp script file appears to show the extra task grouping.

### ISSUE THREAD

**Issue by tiansin** [spmeesseman/vscode-taskexplorer#20]
@spmeesseman 
![1](https://user-images.githubusercontent.com/4232281/56436624-12a56800-630f-11e9-8356-659fcaf35d64.gif)

**Comment by spmeesseman** [comment]
ok this one is fixed.  I'll push 1.14.8 out in the morning EDT and look at that other one again tonight see if i can squeeze that fix in there too

just a note... Gulpfiles in the project root are detected by VSCode internally.  So the task you are executing isnt provided by the extension.  Which is fine except for one thing, when you save changes in a gulpfile, the task provider in vscode does not notify me of the change, so i dont know to refresh the tree node.   Its on my tasklist to chang that behavior, to ignore the internally provided tasks by vscode, and detect them with the extensions provider instead
