### ISSUE TITLE
provide API

### ISSUE THREAD

**Issue by WebFreak001** [spmeesseman/vscode-taskexplorer#22]
hi, I would like to contribute tasks to your extension with my extension. Is there a possibility you could provide your TaskProvider API to the outside? (See https://code.visualstudio.com/api/references/vscode-api#extensions)

**Comment by spmeesseman** [comment]
i will look into it :)

**Comment by WebFreak001** [comment]
specifically, because I saw you are using the standard tasks API, I would like to be able to provide like an icon for my group. Also because right now your extension groups my tasks under "vscode" and often they are not there at all if there are other things in the workspace

**Comment by spmeesseman** [comment]
hi.  the next release will have this functionality.

**Comment by WebFreak001** [comment]
nice, thanks!

**Comment by spmeesseman** [comment]
soon, ill add a new section to the readme

**Comment by WebFreak001** [comment]
is getting the API object through a command stable or is there a reason to use a command?

It's not the default way of getting it through `vscode.extensions.getExtension("spmeesseman.vscode-taskexplorer")?.exports` and I'm not sure if it plays well with remote setups where it might need to serialize and forward the commands over network.

For that way you just return the API object in the activate function, then it's in the `exports` field of the getExtension call. It also allows to test if the extension is installed in the same call very easily.
