### ISSUE TITLE
suggestion: clicking on the task could switch to the task terminal if active

### ISSUE THREAD

**Issue by xaviergonz** [spmeesseman/vscode-taskexplorer#23]
I think it would be cool if  clicking on a running task would focus the terminal that's running such task (be it by clicking it directly when it is running, via some setting or through a button near the "stop" button)

Or maybe double clicking + button
Also double clicking could start a task if not already started

**Comment by xaviergonz** [comment]
or double clicking

**Comment by spmeesseman** [comment]
i will look into it :)

**Comment by spmeesseman** [comment]
1.24

**Comment by drschwabe** [comment]
A suggestion regarding this feature.  Current UI is setup such that clicking on task (of a running task) name opens the configuration file for said task.  And to open the terminal you must click one of the three small icons to the right of said task name. 

I propose swapping those two such that the terminal opens when you click on name of running task; and a little gear icon perhaps for the opening of it's config file.   

Those little icons require precious mental energy to pinpoint and click on; rarely need to edit the task but frequently in and out of the task's terminal.
