### ISSUE TITLE
NPM and TSC Tasks not excluded

### ISSUE THREAD

**Issue by SupinePandora43** [spmeesseman/vscode-taskexplorer#29]
### Steps to reproduce ###
add "**\***" to "**taskExplorer.exclude**"

**Comment by spmeesseman** [comment]
this is a bug in the latest visual studio code npm task provider, i noticed the issue too, can you confirm you are running the latest?  (1.34)

**Comment by SupinePandora43** [comment]
@spmeesseman latest.

**Comment by spmeesseman** [comment]
ok, yeah.  im sure theyll have it fixed in the next path or release
