### ISSUE TITLE
Add configuration option to not show the Terminal when a task is run

### ISSUE THREAD

**Issue by robertrossmann** [spmeesseman/vscode-taskexplorer#39]
I would love to have a flag which would cause the auto-detected tasks to _not_ open up the Terminal view when a task is run (ie. a "silent" execution). The task's output would still be accessible on-demand in the Terminal view but the view itself would remain hidden unless explicitly shown by the user.

I execute compile tasks almost after every file save and get quite annoyed by the terminal view constantly popping out. Most of the time I am only interested in seeing the final result (success/failure) of a task run which I can see in the status bar anyway.

Thank you for consideration! ❤️

**Comment by spmeesseman** [comment]
woops wrong ticket

**Comment by richarddavenport** [comment]
@spmeesseman is this still up for grabs? I don't see this option available?

**Comment by spmeesseman** [comment]
9 months later... yeah, sorry, i dont know how it got tagged released, probably ref'd the wrong ticket # in a commit, still up for grabs

**Comment by spmeesseman** [comment]
implemented in v1.30.  but...
note that as of VSCode 1.53, there seems to be a bug that prevents running tasks without showing the terminal:

    https://github.com/microsoft/vscode/issues/116015

WHen this is fixed, this functionality "should" then work.
