### ISSUE TITLE
gulp tasks are not detected

### ISSUE THREAD

**Issue by stefano-b** [spmeesseman/vscode-taskexplorer#41]
As the title says, gulp tasks are not detected.

My `gulpfile.js` is written according to the [official documentation](https://gulpjs.com/docs/en/getting-started/creating-tasks) and the tasks are accordingly exported in this way:

```
const { series } = require('gulp');

// The `clean` function is not exported so it can be considered a private task.
// It can still be used within the `series()` composition.
function clean(cb) {
  // body omitted
  cb();
}

// The `build` function is exported so it is public and can be run with the `gulp` command.
// It can also be used within the `series()` composition.
function build(cb) {
  // body omitted
  cb();
}

exports.build = build;
exports.default = series(clean, build);
```

Running gulp from terminal correctly detects, shows and executes them:

```
> gulp --tasks
[14:52:29] Tasks for ~/test/gulpfile.js
[14:52:29] ├── build
[14:52:29] └─┬ default
[14:52:29]   └─┬ <series>
[14:52:29]     ├── clean
[14:52:29]     └── build
```
I tried with some other extensions (i.e. [this one](https://marketplace.visualstudio.com/items?itemName=cnshenj.vscode-task-manager)) and they can detect and run them.

Could it be possible to fix this? If there is some more info that I can provide, please ask.

**Comment by spmeesseman** [comment]
currently it will only pick up gulp.task

gulp.task('test', (done) => {
    console.log('test gulp subdir task!');
    done();
});
