### ISSUE TITLE
Feature Request: Add current task in the header

### ISSUE THREAD

**Issue by RUSshy** [spmeesseman/vscode-taskexplorer#47]
Something like that:

A drop down menu:

![image](https://user-images.githubusercontent.com/18348637/67272273-8ee65700-f4bc-11e9-8dcb-0e9fbdb47761.png)

Easier to manage multiple projects solutions, or multiple scripts

**Comment by spmeesseman** [comment]
how would putting a dropdown or label indicating the current running task make management any easier?

**Comment by RUSshy** [comment]
so i know what task it's gonna run

there is no visual indication what the play button gonna do, this is UX issue

**Comment by spmeesseman** [comment]
But the task that runs is the one you click "Run Task" for...  Still not understanding... do you mean when you're running several tasks at one time?
I guess I could see something to make it easier if you run several tasks at once, but running one task at a time that wouldnt make sense, its not a UI issue its just an opinion.
If I could think of something nice for managing more than one running task at a time, I will surely put it in, Ill think on it if that's what you meant...
