### ISSUE TITLE
Ant file import lookup

### ISSUE THREAD

**Issue by bm-stschneider** [spmeesseman/vscode-taskexplorer#5]
If in a build.xml file other xml file for ant are imported via a fileset it would be nice if that would be resolved.

**Comment by spmeesseman** [comment]
My idea for addressing this was to add a setting for including files other than just build.xml to parse for Ant targets.  In this way all targets are found even if they arent referenced from an existing build.xml.  But I'll also look into what you mean exactly when I get into this one, I have experience with only basic ant scripts so I'll be sure to examine the best ways to handle this.

**Comment by spmeesseman** [comment]
Can you give me an example of importing another ant file via fileset?  I've used something like this before:

<ant antfile="CopyDependencies.xml" dir="script" target="copy" />

which I could parse that file as well (CopyDependecies.xml) but have not "imported" an ant file via fileset before

**Comment by bm-stschneider** [comment]
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Use "ant -p" to get an overview over all available targets. -->
<project name="default" default="build">
    <import>
        <fileset dir="${basedir}/app/ant/lib" includes="*.xml"/>
    </import>
    <property environment="env"/>

</project>
```

**Comment by spmeesseman** [comment]
Ah, <import>, ok.  I could add this is a future release.  I did add support to scan for files not named [Bb]uild.xml in 1.8 (they need to be located somewhere in the project dir though).  Is this sufficient for what you need? (for now).  So to your settings.json you could add:

    taskExplorer.includeAnt: [ "/app/ant/lib/*.xml" ]

 I believe would do the trick

**Comment by bm-stschneider** [comment]
That would do the trick thank you.

**Comment by spmeesseman** [comment]
Added handling import to the todo list, but its down there, closing this since we provided a workaround for now
