### ISSUE TITLE
Add ability to run default ANT task

### ISSUE THREAD

**Issue by dswitzer** [spmeesseman/vscode-taskexplorer#50]
First, thanks for such a useful extension. This is exactly what I've been wanting!

I would love to see the "default" ANT task supported, by offering a "play" button to the right of the build name (like you see when viewing the individual tasks in the ANT build script).

We have a large code base that uses lots of ANT scripts. They all have a default task defined, but unfortunately the default task name is standardized, so I don't always remember which task I need to run.

If there was a play button to right of each ANT task that has a "default" task configured, this would make things much easier. Just click the play button to run the task.

**Comment by spmeesseman** [comment]
i can add that when i have some time, thanks for the feedback :)

**Comment by dswitzer** [comment]
@spmeesseman,

Thanks! This is very helpful. 

If you ever consider any additional enhancements, I'd love to just have a play button on the ANT script itself which plays the default task, but the "(Default)" label is a huge help. Thanks again!
