### ISSUE TITLE
vscode-taskexplorer/vscode-gradle 2 plugins is conflicted

### ISSUE THREAD

**Issue by zengfr** [spmeesseman/vscode-taskexplorer#53]
vscode-taskexplorer/vscode-gradle 2 plugins is conflicted
see:
https://github.com/badsyntax/vscode-gradle/issues/37
https://github.com/spmeesseman/vscode-taskexplorer/issues/52

**Comment by spmeesseman** [comment]
i will look into when i get some time, thanks for the feedback

**Comment by spmeesseman** [comment]
wont have time for this anytime soon, i suggest turning off gradle tasks in Task Explorer settings if you need to use the other extension
