### ISSUE TITLE
Alternate Gulpfile Names are Not Supported

### ISSUE THREAD

**Issue by whschultz** [spmeesseman/vscode-taskexplorer#73]
Gulp supports writing the Gulpfile in languages other than Javascript, taking advantage of a transpiler, like Babel.  The [documentation](https://gulpjs.com/docs/en/getting-started/javascript-and-gulpfiles#transpilation) isn't thorough, but from experience, I know at least the following filenames are supported:

- gulpfile.js
- gulpfile.babel.js
- gulpfile.ts
- gulpfile.babel.ts

**Comment by spmeesseman** [comment]
i would need examples of a gulp script written in typescript, can you supply these please?  i dont use gulp, just go off exaples others have given me to work off of

**Comment by whschultz** [comment]
Probably a better approach is that if any of these files exist, run the following command:

`npx gulp --tasks-simple`

This would work no matter how they format their configuration file, and it would use Gulp to determine what the list of tasks is.  In my case, this would work better than parsing the file, since some of my tasks are dynamically generated based on configuration files.  The output would look something like this:

```
$ npx gulp --tasks-simple
services:clean:edge-configuration
services:generate:edge-configuration
prepEnvironment
services:clean
services:generate
compile:lib
services:build
bundle:lib
compile:app
watch:src
watch:lib
watch:app
watch
default
```

**Comment by ray007** [comment]
This would also help with the extension currently not finding gulp4 task which are exported as quoted properties:
```
exports['build:release'] = fnTaskRelease;
```
will currently not be found.

**Comment by spmeesseman** [comment]
> Probably a better approach is that if any of these files exist, run the following command:
> 
> `npx gulp --tasks-simple`
> 
> This would work no matter how they format their configuration file, and it would use Gulp to determine what the list of tasks is. In my case, this would work better than parsing the file, since some of my tasks are dynamically generated based on configuration files. The output would look something like this:
> 
> ```
> $ npx gulp --tasks-simple
> services:clean:edge-configuration
> services:generate:edge-configuration
> prepEnvironment
> services:clean
> services:generate
> compile:lib
> services:build
> bundle:lib
> compile:app
> watch:src
> watch:lib
> watch:app
> watch
> default
> ```

id like to stay away from using the actual program to detect tasks, id like to to parse the script.  so any examples you can provide of task defs that are not picked up, please pass them on

**Comment by spmeesseman** [comment]
> This would also help with the extension currently not finding gulp4 task which are exported as quoted properties:
> 
> ```
> exports['build:release'] = fnTaskRelease;
> ```
> 
> will currently not be found.

i will add support for this type of task def in future release as soon as i have a chance

**Comment by whschultz** [comment]
> > Probably a better approach is that if any of these files exist, run the following command:
> > `npx gulp --tasks-simple`
> > This would work no matter how they format their configuration file, and it would use Gulp to determine what the list of tasks is. In my case, this would work better than parsing the file, since some of my tasks are dynamically generated based on configuration files. The output would look something like this:
> > ```
> > $ npx gulp --tasks-simple
> > services:clean:edge-configuration
> > services:generate:edge-configuration
> > prepEnvironment
> > services:clean
> > services:generate
> > compile:lib
> > services:build
> > bundle:lib
> > compile:app
> > watch:src
> > watch:lib
> > watch:app
> > watch
> > default
> > ```
> 
> id like to stay away from using the actual program to detect tasks, id like to to parse the script. so any examples you can provide of task defs that are not picked up, please pass them on

```
function createCssTasks(name) {
    const bundleTaskName = `bundle:${name}Css`;
    const minifyTaskName = `minify:${name}Css`;
    const watchTaskName = `watch:${name}Css`;

    const bundle = paths.cssBundles[name];

    gulp.task(bundleTaskName, function doBundleCss() {
        ...
    });

    gulp.task(minifyTaskName,
        ...
    );

    gulp.task(watchTaskName, function doWatchCss(done) {
        ...
    });
```

Basically, anything dynamically generated isn't going to be picked up by static analysis.  Unfortunately, I haven't found a VSCode extension that will simply ask gulp what the tasks are and lets me configure where the gulpfile is.  Therefore, any time I've done this, these auto-generated tasks don't show up.  In the above example, it's done to reduce code duplication.  In another case, I've done it so that configuration of services is centralized in a JSON file.

**Comment by ray007** [comment]
@spmeesseman wrote:
> id like to stay away from using the actual program to detect tasks, id like to to parse the script. so any examples you can provide of task defs that are not picked up, please pass them on

What's the reason for not using the actual program to get a list of tasks? Since you need to be able to run the program for task-execution anyway...

**Comment by spmeesseman** [comment]
ok ok ill do it.  ;)  when i have some time though

**Comment by spmeesseman** [comment]
added support for the bracketed tasks but next minor version ill have what you guys are requestign in there

**Comment by whschultz** [comment]
Wonderful!  Thanks!
