### ISSUE TITLE
how to keep the "task.json" not opened when single click the task item on the left?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [spmeesseman/vscode-taskexplorer#87]
as title, here is the screenshot, when i click any item, the task.json will be opened, it seems to be boring.

![image](https://user-images.githubusercontent.com/7458713/77268942-7f28a400-6ce2-11ea-85bf-ab2301c51400.png)

what i wish is just execute the task, focusing on the item also can be accepted when i making single click on the item.

**Comment by ziyouchutuwenwu** [comment]
my vscode info:
```bash
版本: 1.43.1
提交: fe22a9645b44368865c0ba92e2fb881ff1afce94
日期: 2020-03-18T07:17:38.324Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.19.0-8-amd64
```

**Comment by spmeesseman** [comment]
this is expected behavior.  To execute the task like you are saying, click the 'execute' button on the task item, .  to open a running task, click the 'open task' button on the task item.  to stop a running task, click the 'stop' button on the task item.
