### ISSUE TITLE
List of tasks not filtered until restart

### ISSUE THREAD

**Issue by jsedanoj** [spmeesseman/vscode-taskexplorer#92]
Hi,

  I have found what seems to be a bug. I have a PHP project developed in VSCode 1.44.1 (using Remote Containers [https://code.visualstudio.com/docs/remote/containers]), and using Makefile for the build process. So Task Explorer looks ideal (and it is!). Task Explorer 1.26.3.

The project is open source and can be use for testing the bug here: https://gitlab.com/javier.sedano/vaca/-/tree/master

I have configured Task Explorer to exclude vendor/ and bin/.phpunit because they contain some Makefiles and ant files in a workspace .vscode/settings.json:

```
{
    "taskExplorer.enableAnsiconForAnt": false,
    "taskExplorer.enableAppPublisher": false,
    "taskExplorer.enableBatch": false,
    "taskExplorer.enableGrunt": false,
    "taskExplorer.enableGulp": false,
    "taskExplorer.enableGradle": false,
    "taskExplorer.enableNpm": false,
    "taskExplorer.enableNsis": false,
    "taskExplorer.enablePowershell": false,
    "taskExplorer.enablePerl": false,
    "taskExplorer.enablePython": false,
    "taskExplorer.enableBash": false,
    "taskExplorer.enableRuby": false,
    "taskExplorer.enableTsc": false,
    "taskExplorer.pathToMake": "make",
    "taskExplorer.groupDashed": true,
    "taskExplorer.numLastTasks": 1,
    "taskExplorer.exclude": ["vendor/**", "bin/.phpunit/**"]
}
```

At first, it works as expected and shows the make targets of my Makefile (notice that in this very moment, the exclusion is still irrelevant because such directories do not even exist):

![image](https://user-images.githubusercontent.com/12848713/79542294-abd69e00-808b-11ea-882b-4519e16691c9.png)

Then, I download the dependencies so vendor/ is populated; and run the phpunit tests to bin/.phpunit is populated, and TaskExplorer shows too much tasks:

![image](https://user-images.githubusercontent.com/12848713/79545080-68caf980-8090-11ea-99b1-eacc69dab5a2.png)

Ugly. I restart VSCode and the wrong makefiles disappear again :-)

![image](https://user-images.githubusercontent.com/12848713/79545633-4dacb980-8091-11ea-82e2-f0b4c05047f7.png)

Cool again. I can live with it, but I wanted to report it.

**Comment by spmeesseman** [comment]
thanks for the report, i will look into as soon as i have a chance
