### ISSUE TITLE
Code Helper (GPU) High CPU Usage

### ISSUE THREAD

**Issue by janviehweger** [spmeesseman/vscode-taskexplorer#93]
When running an npm task from the "Task Explorer" panel cpu usage rises up to 60% on 16Gig MacBook Pro (Retina, 15', Mid 2014) with Catalina 10.15.4 with VSCode 1.44.2

<img width="722" alt="Bildschirmfoto 2020-04-27 um 13 44 25" src="https://user-images.githubusercontent.com/376219/80364025-dabff180-888d-11ea-9d8c-2fc14460397f.png">

When running the task from cmd everything works fine.

**Comment by janviehweger** [comment]
> When running an npm task from the "Task Explorer" panel cpu usage rises up to 60% on 16Gig MacBook Pro (Retina, 15', Mid 2014) with Catalina 10.15.4 with VSCode 1.44.2
> 
> <img alt="Bildschirmfoto 2020-04-27 um 13 44 25" width="722" src="https://user-images.githubusercontent.com/376219/80364025-dabff180-888d-11ea-9d8c-2fc14460397f.png">

**Comment by janviehweger** [comment]
accidentally closed

**Comment by spmeesseman** [comment]
i will look into this when i get some time, pretty positive i wont be able to reproduce though.
Quesion -
what is the cpu usage running that particular command from the VSCode command palette?

**Comment by ArthurCarli** [comment]
Hello,
I have the similar issue. 
It is when the 'Last Tasks' pseudo folder is activated and unfolded, with some long running tasks active inside (with the rotating gif), the CPU  usage of the GPU sub process goes high. If I fold the 'Last Tasks' folder, the CPU Usage goes back to normal:
Folded:
![image](https://user-images.githubusercontent.com/43670852/87009680-cff6d680-c1c5-11ea-9ddb-74b51b67b0e3.png)
Unfolded:
![image](https://user-images.githubusercontent.com/43670852/87009794-f87ed080-c1c5-11ea-9f08-1f1beddb6e62.png)

Here with 2 long running tasks I jumps from 1 to 30 %, but as I have some time, 5 to 6 long running tasks in //, the CPU can go very high

**Comment by jwarkentin** [comment]
I have this same issue and was just looking to see if it's already been reported. It happens whenever I start a long running task such as `npm start` to run a development server. @ArthurCarli is right on the money. Turns out it's all caused by the spinner. As soon as I fold the section showing the spinner the CPU usage goes back down to nothing.

**Comment by spmeesseman** [comment]
not sure if anything can be done on my end, this is simply an svg provided to the TreeItem interface in VSCode, the Electron renderer is more likely the culprit than anything.  But with thousands of users and only a few reports of this, pretty sure theres nothing i can do.  feel free to take a stab at it yourselves all, with a PR.  Sorry about that! :)

**Comment by jwarkentin** [comment]
@spmeesseman What about an option for a static running task indicator instead of the spinner? That seems to be the culprit and would be an easy solution.
