### ISSUE TITLE
Add WSL support

### ISSUE THREAD

**Issue by ReinRalle** [spmeesseman/vscode-taskexplorer#94]
Hello,

is it possible to improve settings for it?

such as:
* `"taskExplorer.pathToBatch": "/mnt/c/Windows/system32/cmd.exe /C"`

thx

btw: I like your program very much 😃

**Comment by spmeesseman** [comment]
sure thing, i will add something like that in next release, as soon as I get some time

And thank you, appreciate you commenting, im glad it is helping you

**Comment by spmeesseman** [comment]
dup #43
