### ISSUE TITLE
Enhancement - provide option to run task when clicking on description

### ISSUE THREAD

**Issue by jmooring** [spmeesseman/vscode-taskexplorer#97]
This extension is excellent. Thank you. 

Perhaps I haven't used it enough yet, but I find myself frequently opening the files in which the tasks are defined instead of running the task. It would be great if I could disable that functionality, and just run the task whether I click on the task description or the ▶.

**Comment by spmeesseman** [comment]
2nd request for this, so ill look at adding the option when i can get some time
